imports:
    - { resource: config.yml }
    - { resource: bundles/nelmio_cors.yml }

parameters:
    database_name: campr
    database_password: campr
    domain: qa.campr.biz

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler:
        only_exceptions: false
        dsn: 'file:/var/www/qa.campr.biz/shared/var/profiler/%kernel.environment%'

web_profiler:
    toolbar: true
    intercept_redirects: false

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
