imports:
    - { resource: config.yml }

parameters:
    database_name: campr
    database_password: campr

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels:
        - "portal"
        - "cloner"
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event, !cloner]
        console:
            type:   console
            channels: [!event, !doctrine, !portal, !cloner]
        portal:
            type: stream
            path: "%kernel.logs_dir%/portal.log"
            level: info
            channels: ["portal"]
        cloner:
            type: stream
            path: "%kernel.logs_dir%/cloner.log"
            level: info
            channels: ["cloner"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com
