imports:
    - { resource: config.yml }

parameters:
    domain: test.campr.biz

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false, collect: false }
    test: ~
    session:
        storage_id: session.storage.mock_file

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    channels:
        - "portal"
        - "cloner"
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        portal:
            type: stream
            path: "%kernel.logs_dir%/portal.log"
            level: info
            channels: ["portal"]
        cloner:
            type: stream
            path: "%kernel.logs_dir%/cloner.log"
            level: info
            channels: ["cloner"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com
