portal:
    resource: "@PortalBundle/Controller/"
    type: annotation
    prefix: /
    defaults:
        subdomain: "%kernel.team_slug%"

main:
    resource: "@MainBundle/Controller/"
    type:  annotation
    host: "{domain}"
    prefix: /
    defaults:
        domain: "%domain%"
    requirements:
        domain: "%domain%"

app:
    resource: "@AppBundle/Controller/"
    type: app
    host: "{subdomain}.%domain%"
    defaults:
        subdomain: "%kernel.team_slug%"

portal_routes:
    resource: routing_portal.yml

api_login_check:
    path: /api/login-check

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

translation:
    resource: "@TranslationBundle/Resources/config/routing_symfony_profiler.yml"

app_uploader_url:
    path: '{path}'
    requirements:
        path: ((?!_wdt|_profiler).)+
