gos_web_socket:
    server:
        port: 1558          #The port the socket server will listen on
        host: 0.0.0.0       #The host ip to bind to
        router:
            resources:
                - '@AppBundle/Resources/config/pubsub/routing.yml'
    client:
        firewall: main
        session_handler: "@session.handler.redis"
        storage:
            driver: "@gos_web_socket.client_storage.driver.redis"
            decorator: "@gos_web_socket.client_storage.doctrine.decorator"
            ttl: 28800
            prefix: client_
