# https://github.com/nelmio/NelmioCorsBundle
nelmio_cors:
    defaults:
        allow_credentials: true
        max_age: 86400
    paths:
        '^/api/':
            allow_origin:
                - 'http://localhost'
                - 'http://localhost:8080'
                - 'https://localhost'
                - 'https://localhost:8080'
                - 'http://%domain%:8080'
                - 'https://%domain%:8080'
                - 'http://%domain%:2080'
                - 'https://%domain%:2080'
            allow_headers: ['Authorization', 'Content-Type', 'X-Requested-With']
            allow_methods: ['OPTIONS', 'POST', 'PUT', 'PATCH', 'GET', 'DELETE']
