# https://github.com/nelmio/NelmioCorsBundle
nelmio_cors:
    defaults:
        allow_credentials: true
        max_age: 86400
    paths:
        '^/api/':
            allow_origin:
                - '*'
            allow_headers:
                - 'Authorization'
                - 'DNT'
                - 'X-CustomHeader'
                - 'Keep-Alive'
                - 'User-Agent'
                - 'X-Requested-With'
                - 'If-Modified-Since'
                - 'Cache-Control'
                - 'Content-Type'
                - 'Content-Range'
                - 'Range'
            allow_methods: ['OPTIONS', 'POST', 'PUT', 'PATCH', 'GET', 'DELETE']
