stages:
  - test
  - deploy

test:phpunit:
  stage: test
  script:
    - export SYMFONY_ENV=test
    - rm -rf var/cache/*
    - wget https://getcomposer.org/composer.phar
    - cp backend/app/config/parameters_test.yml.dist backend/app/config/parameters_test.yml
    - php composer.phar install --quiet --prefer-dist --no-interaction
    - cp phpunit.xml.dist phpunit.xml
    - rm -rf web/uploads/tests
    - mkdir -p backend/src/AppBundle/Tests/Resources/files/ && touch backend/src/AppBundle/Tests/Resources/files/file.txt
    - bin/console doctrine:database:drop --if-exists --force --env=test
    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:migrations:migrate --no-interaction --env=test
    - bin/console doctrine:schema:validate --env=test
    - bin/console doctrine:fixtures:load --append --fixtures=backend/src/AppBundle/DataFixtures/ORM/ --no-interaction --env=test
    - bin/console cache:clear --env=test
    - backend/vendor/bin/phpunit -c . backend/src
    - rm -rf backend/src/AppBundle/Tests/Resources/files/

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
    - export SYMFONY_ENV=qa
    - wget https://getcomposer.org/composer.phar
    - cp backend/app/config/parameters_qa.yml.dist backend/app/config/parameters_qa.yml
    - php composer.phar install --quiet --prefer-dist --no-interaction
    - bin/console cache:clear --env=qa
    - cp -r . /var/www/$CI_COMMIT_REF_SLUG.qa.campr.biz/current
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.qa.campr.biz
  when: manual
  #only:
  #  - branches
  #except:
  #  - master
