stages:
  - test

before_script:
  - export SYMFONY_ENV=test
  - rm -rf var/cache/*
  - wget https://getcomposer.org/composer.phar
  - cp backend/app/config/parameters_test.yml.dist backend/app/config/parameters_test.yml
  - php composer.phar install --quiet --prefer-dist --no-interaction
  - cp phpunit.xml.dist phpunit.xml
  - rm -rf web/uploads/tests
  - mkdir -p backend/src/AppBundle/Tests/Resources/files/ && touch backend/src/AppBundle/Tests/Resources/files/file.txt
  - bin/console doctrine:database:drop --if-exists --force --env=test
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:migrations:migrate --no-interaction --env=test
  - bin/console doctrine:fixtures:load --append --fixtures=backend/src/AppBundle/DataFixtures/ORM/ --no-interaction --env=test
  - bin/console cache:clear --env=test

test:phpunit:
  stage: test
  script:
    - backend/vendor/bin/phpunit -c . backend/src

after_script:
  - rm -rf backend/src/AppBundle/Tests/Resources/files/
