---
title: Campr
timezone: UTC
collections:
  meta:
    title: Meta
    output: false
    description: CAMPR support page
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
github_url: https://camprgmbh.github.io/campr
theme: jekyll-theme-modernist
url: https://campr.siteleaf.net
