---
title: Campr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  meta:
    description: CAMPR support page
theme: jekyll-theme-modernist

