---
title: Campr
timezone: UTC
collections:
  meta:
    title: Meta
    output: false
    description: CAMPR support page
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-modernist
description: Documentation and learning CAMPR, a Project Management platform designed
  for a better collaboration.
repository: https://github.com/CamprGmbH/campr/tree/gh-pages
