--- 
collections: 
  meta: 
    description: "CAMPR support page"
    output: false
    title: Meta
  posts: 
    output: true
    title: Posts
  uploads: 
    output: true
    title: Uploads
github_url: "https://camprgmbh.github.io/campr"
theme: jekyll-theme-modernist
timezone: UTC
title: Campr
url: "https://campr.siteleaf.net"
