---
title: Campr
timezone: UTC
collections:
  meta:
    title: Meta
    output: false
    description: CAMPR support page
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-modernist
  meta:
      description: Liquid, Sass, Jekyll, syncing, local dev
