version: "2"

volumes:
    db-data:
        external: false

services:
    mailcatcher:
        image: dilibau/mailcatcher:0.6.4
        ports:
            - 1080:1080
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - db-data:/var/lib/mysql
    redis:
        image: redis
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            - MYSQL_ROOT_PASSWORD=root
    php-fpm:
        # build: config/docker/php-fpm
        image: lab.trisoft.ro:4567/trisoft/internal/php-fpm-7.0
        environment:
            - SYMFONY_DEBUG=true
            - SYMFONY_ENV=dev
        depends_on:
            - db
            - redis
            - mailcatcher
        volumes:
            - .:/app
        ports:
            - 2080:8080
    dev.campr.biz:
        # build: config/docker/nginx
        image: lab.trisoft.ro:4567/trisoft/internal/nginx-dev
        depends_on:
            - php-fpm
        volumes_from:
            - php-fpm
        ports:
            - 80:80
    supervisor:
        # build: config/docker/supervisor
        image: lab.trisoft.ro:4567/trisoft/internal/php-supervisor
        volumes:
            - .:/app
            - ./config/supervisor/docker_dev.conf:/etc/supervisor/conf.d/docker_dev.conf
