<?php

namespace AppBundle\Repository;

/**
 * AssignmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
