<?php

namespace AppBundle\Repository;

/**
 * StatusRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorStatusRepository extends BaseRepository
{
}
