<?php

namespace AppBundle\Repository;

/**
 * CommunicationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunicationRepository extends \Doctrine\ORM\EntityRepository
{
}
