<?php

namespace AppBundle\Repository;

/**
 * DecisionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecisionRepository extends \Doctrine\ORM\EntityRepository
{
}
