<?php

namespace AppBundle\Repository;

/**
 * ImpactRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpactRepository extends BaseRepository
{
}
