<?php

namespace AppBundle\Repository;

/**
 * MeetingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingRepository extends BaseRepository
{
}
