<?php

namespace AppBundle\Repository;

/**
 * MeetingParticipantRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingParticipantRepository extends \Doctrine\ORM\EntityRepository
{
}
