<?php

namespace AppBundle\Repository;

/**
 * MeetingAgendaRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingAgendaRepository extends \Doctrine\ORM\EntityRepository
{
}
