<?php

namespace AppBundle\Repository;

/**
 * ProjectWorkCostTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectWorkCostTypeRepository extends BaseRepository
{
}
