<?php

namespace AppBundle\Repository;

/**
 * ProjectCostTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectCostTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
