<?php

namespace AppBundle\Repository;

/**
 * RaciRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaciRepository extends \Doctrine\ORM\EntityRepository
{
}
