<?php

namespace AppBundle\Repository;

/**
 * RiskCategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiskCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
