<?php

namespace AppBundle\Repository;

/**
 * RiskStrategyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiskStrategyRepository extends \Doctrine\ORM\EntityRepository
{
}
