<?php

namespace AppBundle\Repository;

/**
 * RiskRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiskRepository extends \Doctrine\ORM\EntityRepository
{
}
