<?php

namespace AppBundle\Repository;

/**
 * TimephaseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimephaseRepository extends \Doctrine\ORM\EntityRepository
{
}
