<?php

namespace AppBundle\Repository;

/**
 * WorkPackageProjectWorkCostTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkPackageProjectWorkCostTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
