imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_qa.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

parameters:
    database_password: campr

web_profiler:
    toolbar: true
    intercept_redirects: false

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
