main:
    resource: "@MainBundle/Controller/"
    type:  annotation
    host: "%domain%"
    prefix: /

app:
    resource: "@AppBundle/Controller/"
    type: annotation
    host: "{subdomain}.%domain%"
    defaults:
        subdomain: "%kernel.team_slug%"

api_login_check:
    path: /api/login-check

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
