app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /

api_login_check:
    path: /api/login-check

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
