parameters:
    emails:
        from_email:
            info: "info@campr.biz"
            no-reply: "no-reply@campr.biz"
        from_name:
            info: "Info Campr"
            no-reply: "No Reply"
    adapters:
        admin.filesystem.driver.choice.local: "local_adapter"
        admin.filesystem.driver.choice.dropbox: "dropbox_adapter"

services:
    app.service.team:
        class: AppBundle\Services\TeamService
        arguments:
            - '@request_stack'
            - '@redis.client'
            - '%domain%'

    app.jwt_signer:
        class: Lcobucci\JWT\Signer\Hmac\Sha512

    app.jwt_builder:
        class: Lcobucci\JWT\Builder

    app.jwt_parser:
        class: Lcobucci\JWT\Parser

    app.service.mailer:
        class: AppBundle\Services\MailerService
        arguments:
            - "@mailer"
            - "@twig"
            - "%emails%"

    app.service.user:
        class: AppBundle\Services\UserService

    app.service.request_parser:
        class: AppBundle\Services\RequestParserService

    app.service.data_table:
        class: AppBundle\Services\DataTableService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.service.request_parser"
            - "@jms_serializer"
            - "@fos_js_routing.encoder"
            - "@fos_js_routing.normalizer"

    app.service.import:
        class: AppBundle\Services\ImportService
        arguments:
            - "@doctrine.orm.entity_manager"

    app.service.chat:
        class: AppBundle\Services\ChatService
        arguments:
            - "@doctrine.orm.entity_manager"

    redis.client:
        class: Predis\Client
        arguments:
            -
                host: '%redis_host%'

    session.handler.redis:
        class: Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@redis.client'

    app.service.filesystem:
        class: AppBundle\Services\FileSystemService
        arguments:
            - "@knp_gaufrette.filesystem_map"

    app.service.chat_topic:
        class: AppBundle\Topic\ChatTopic
        arguments:
            - "@app.service.chat"
            - "@gos_web_socket.websocket.client_manipulator"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: gos_web_socket.topic }

    app.service.chat_user_topic:
        class: AppBundle\Topic\ChatUserTopic
        arguments:
            - "@app.service.chat"
            - "@gos_web_socket.websocket.client_manipulator"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: gos_web_socket.topic }

    app.menu.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - "@router"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@translator"

    app.admin_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.menu_builder", createAdminAppMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: admin_app }

### FORM TYPES ###
    app.form.filesystem.create_type:
        class: AppBundle\Form\FileSystem\CreateType
        arguments:
            - "%adapters%"
        tags:
            - { name: form.type }

    app.form.filesystem.media_upload_type:
        class: AppBundle\Form\FileSystem\MediaUploadType
        arguments:
            - "@security.token_storage"
        tags:
            - { name: form.type }

### LISTENERS ###
    # gedmo listeners are found here
    # https://github.com/Atlantic18/DoctrineExtensions/blob/a3d7ad1cf41f397104bc16d99c0a91fd7b2e6d38/doc/symfony2.md
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    app.listener.updated_at:
        class: AppBundle\EventListener\UpdatedAtListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    app.listener.user:
        class: AppBundle\EventListener\UserListener
        arguments:
            - '@app.service.user'
            - '@security.password_encoder'
        tags :
            - { name: doctrine.event_listener, event: onFlush }

    app.listener.media:
        class: AppBundle\EventListener\MediaListener
        arguments:
            - '@app.service.filesystem'
        tags :
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preRemove }

    app.listener.db_logger:
        class: AppBundle\EventListener\DBLogger
        tags:
            - { name: doctrine.event_listener, event: onFlush }
        arguments:
            - "@security.token_storage"

    app.listener.message:
        class: AppBundle\EventListener\MessageListener
        tags :
            - { name: doctrine.event_listener, event: prePersist }

### EXTENSIONS ###
    app.app_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

### SUBSCRIBERS ###
    ambta_doctrine_encrypt.subscriber:
        class: AppBundle\Subscribers\EncryptSubscriber
        arguments: ["@annotation_reader", "%ambta_doctrine_encrypt.encryptor_class_name%", "%ambta_doctrine_encrypt.secret_key%"]
        tags:
            -  { name: doctrine.event_subscriber }

### VOTERS ###
    app.project_voter:
        class: AppBundle\Security\ProjectVoter
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: security.voter }
        public: false
