parameters:
    emails:
        from_email:
            info: "info@campr.biz"
            no-reply: "no-reply@campr.biz"
        from_name:
            info: "Info Campr"
            no-reply: "No Reply"

services:
    app.service.mailer:
        class: AppBundle\Services\MailerService
        arguments:
            - "@mailer"
            - "@twig"
            - "%emails%"
    app.service.user:
        class: AppBundle\Services\UserService
    app.service.request_parser:
        class: AppBundle\Services\RequestParserService
    app.service.serializer:
        class: AppBundle\Services\SerializerService
        arguments:
            - "@fos_js_routing.encoder"
            - "@fos_js_routing.normalizer"
    redis.client:
        class: Predis\Client
    session.handler.redis:
        class: Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@redis.client'
    app.service.db_logger:
        class: AppBundle\Services\DBLogger
        tags:
            - { name: doctrine.event_listener, event: onFlush }
        arguments:
            - "@security.token_storage"

### LISTENERS ###
    app.listener.updated_at:
        class: AppBundle\EventListener\UpdatedAtListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
    app.listener.user:
        class: AppBundle\EventListener\UserListener
        arguments:
            - '@app.service.user'
            - '@security.password_encoder'
        tags :
            - { name: doctrine.event_listener, event: onFlush }
