parameters:
    emails:
        from_email:
            info: "info@campr.biz"
            no-reply: "no-reply@campr.biz"
        from_name:
            info: "Info Campr"
            no-reply: "No Reply"

services:
    app.service.mailer:
            class: AppBundle\Services\MailerService
            arguments:
                - "@mailer"
                - "@twig"
                - "%emails%"

