services:
    app.calculator.phase_actual_dates:
        class: Component\WorkPackage\Calculator\PhaseActualDatesCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.phase_forecast_dates:
        class: Component\WorkPackage\Calculator\PhaseForecastDatesCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.milestone_actual_dates:
        class: Component\WorkPackage\Calculator\MilestoneActualDatesCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.milestone_forecast_dates:
        class: Component\WorkPackage\Calculator\MilestoneForecastDatesCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.phase_status:
        class: Component\WorkPackage\Calculator\PhaseStatusCalculator
        arguments:
            - '@app.repository.work_package'
            - '@app.repository.work_package_status'

    app.calculator.milestone_status:
        class: Component\WorkPackage\Calculator\MilestoneStatusCalculator
        arguments:
            - '@app.repository.work_package'
            - '@app.repository.work_package_status'

    app.calculator.project_scheduled_dates:
        class: Component\Project\Calculator\ProjectScheduledDatesCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.project_forecast_dates:
        class: Component\Project\Calculator\ProjectForecastDatesCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.project_actual_dates:
        class: Component\Project\Calculator\ProjectActualDatesCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.project_progress:
        class: Component\Project\Calculator\ProjectProgressCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.work_package_progress:
        class: Component\WorkPackage\Calculator\WorkPackageProgressCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.project_total_cost:
        class: Component\Cost\Calculator\ProjectTotalCostCalculator
        arguments:
            - '@app.repository.work_package'
            - '@app.repository.cost'

    app.calculator.project_workpackage_status_total_count:
        class: Component\Project\Calculator\WorkPackageStatusTotalCountCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.project_workpackage_traffic_light_total:
        class: Component\Project\Calculator\WorkPackageTrafficLightTotalCalculator
        arguments:
            - '@app.repository.work_package'

    app.calculator.project_risk_total:
        class: Component\Project\Calculator\RiskTotalCalculator
        arguments:
            - '@app.repository.risk'
            - '@app.repository.measure'

    app.calculator.project_opportunity_total:
        class: Component\Project\Calculator\OpportunityTotalCalculator
        arguments:
            - '@app.repository.opportunity'
            - '@app.repository.measure'

    app.calculator.days_elapsed_progress:
        class: Component\Calculator\DaysElapsedProgressCalculator

    app.calculator.project_planned_progress:
        class: Component\Project\Calculator\ProjectPlannedProgressCalculator
        arguments:
            - '@app.calculator.days_elapsed_progress'

