services:
    app.serializer.listener.team:
        class: AppBundle\Serializer\EventListener\TeamSubscriber
        arguments:
            - '@app.uploader.url_resolver.team_logo'
        tags:
          - { name: jms_serializer.event_subscriber }
    app.serializer.listener.project:
        class: AppBundle\Serializer\EventListener\ProjectSubscriber
        arguments:
             - '@app.calculator.project_scheduled_dates'
             - '@app.calculator.project_forecast_dates'
             - '@app.calculator.project_actual_dates'
             - '@app.calculator.project_total_cost'
             - '@app.calculator.project_progress'
             - '@app.uploader.url_resolver.project_logo'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.work_package:
        class: AppBundle\Serializer\EventListener\WorkPackageSubscriber
        arguments:
            - '@app.calculator.work_package_progress'
            - '@app.calculator.phase_forecast_dates'
            - '@app.calculator.phase_actual_dates'
            - '@app.calculator.milestone_forecast_dates'
            - '@app.calculator.milestone_actual_dates'
            - '@app.calculator.phase_status'
            - '@app.calculator.milestone_status'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.avatar_aware:
        class: AppBundle\Serializer\EventListener\AvatarAwareSubscriber
        arguments:
            - '@app.resolver.avatar.url'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.meeting:
        class: AppBundle\Serializer\EventListener\MeetingSubscriber
        arguments:
             - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.log:
        class: AppBundle\Serializer\EventListener\LogSubscriber
        arguments:
             - '@app.repository.project_user'
             - '@app.repository.user'
             - '@doctrine.orm.entity_manager'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.contract:
      class: AppBundle\Serializer\EventListener\ContractSubscriber
      arguments:
        - '@app.snapshot.transformer.risks'
        - '@app.snapshot.transformer.opportunities'
      tags:
        - { name: jms_serializer.event_subscriber }

    app.serializer.normalizer.json:
        class: AppBundle\Serializer\Normalizer\JsonSerializableNormalizer
        arguments:
            - '@jms_serializer'
