services:
    app.serializer.listener.project:
        class: AppBundle\Serializer\EventListener\ProjectSubscriber
        arguments:
             - '@app.calculator.project_scheduled_dates'
             - '@app.calculator.project_forecast_dates'
             - '@app.calculator.project_actual_dates'
             - '@app.calculator.project_total_cost'
             - '@app.calculator.project_progress'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.work_package:
        class: AppBundle\Serializer\EventListener\WorkPackageSubscriber
        arguments:
            - '@app.calculator.work_package_progress'
            - '@app.calculator.phase_forecast_dates'
            - '@app.calculator.phase_actual_dates'
            - '@app.calculator.milestone_forecast_dates'
            - '@app.calculator.milestone_actual_dates'
            - '@app.calculator.phase_status'
            - '@app.calculator.milestone_status'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.user:
        class: AppBundle\Serializer\EventListener\UserSubscriber
        arguments:
             - '@app.resolver.user_avatar_url'
             - '@app.resolver.user_uploaded_avatar_url'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.info:
        class: AppBundle\Serializer\EventListener\InfoSubscriber
        arguments:
             - '@app.resolver.user_avatar_url'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.decision:
        class: AppBundle\Serializer\EventListener\DecisionSubscriber
        arguments:
             - '@app.resolver.user_avatar_url'
        tags:
            - { name: jms_serializer.event_subscriber }

    app.serializer.listener.meeting:
        class: AppBundle\Serializer\EventListener\MeetingSubscriber
        arguments:
             - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: jms_serializer.event_subscriber }
