services:
    app.user_invited_validator:
        class: MainBundle\Validator\Constraints\TeamMember\UserInvitedValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator }

    app.self_invite_validator:
        class: MainBundle\Validator\Constraints\TeamMember\SelfInviteValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator }

    app.team_member_validator:
        class: MainBundle\Validator\Constraints\TeamMember\ActiveMemberValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator }

    app.validators.workpackage_assignments:
        class: AppBundle\Validator\Constraints\WorkPackageAssignmentsValidator
        tags:
            - { name: validator.constraint_validator }

    app.validators.sequence:
        class: AppBundle\Validator\Constraints\SequenceValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator }

    app.validators.at_least_one_admin:
        class: AppBundle\Validator\Constraints\AtLeastOneAdminValidator
        arguments:
            - '@app.repository.user'
        tags:
            - { name: validator.constraint_validator }
