imports:
    - { resource: services.yml }

eight_points_guzzle:
    clients:
        portal_api:
            base_url: "%portal.api.base_url%"
            options:
                timeout: '%portal.api.timeout%'
                headers:
                    User-Agent: 'Campr Workspaces'
                    Content-Type: 'application/json'
                    Host: '%portal.api.host%'
            plugin: ~
