<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20181107173714 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf('mysql' != $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE color_status');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB71010AC05');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7166D1F9C');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7385A88B7');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB74B3E2EDA');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB799091188');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7A40A2C8');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7A73A0B9D');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7EFF0A1F4');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB71010AC05 FOREIGN KEY (work_package_category_id) REFERENCES work_package_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7385A88B7 FOREIGN KEY (responsibility_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB74B3E2EDA FOREIGN KEY (milestone_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB799091188 FOREIGN KEY (phase_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7A73A0B9D FOREIGN KEY (work_package_status_id) REFERENCES work_package_status (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7EFF0A1F4 FOREIGN KEY (accountability_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE work_package_label DROP FOREIGN KEY FK_DB7E2E3B33B92F39');
        $this->addSql('ALTER TABLE work_package_label DROP FOREIGN KEY FK_DB7E2E3BEF2F062C');
        $this->addSql('ALTER TABLE work_package_label ADD CONSTRAINT FK_DB7E2E3B33B92F39 FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_label ADD CONSTRAINT FK_DB7E2E3BEF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_dependency DROP FOREIGN KEY FK_14FAB8C6B3D00E54');
        $this->addSql('ALTER TABLE work_package_dependency DROP FOREIGN KEY FK_14FAB8C6C2F67723');
        $this->addSql('ALTER TABLE work_package_dependency ADD CONSTRAINT FK_14FAB8C6B3D00E54 FOREIGN KEY (dependant_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_dependency ADD CONSTRAINT FK_14FAB8C6C2F67723 FOREIGN KEY (dependency_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_comment DROP FOREIGN KEY FK_89DC4D52EF2F062C');
        $this->addSql('ALTER TABLE work_package_comment DROP FOREIGN KEY FK_89DC4D52F8697D13');
        $this->addSql('ALTER TABLE work_package_comment ADD CONSTRAINT FK_89DC4D52EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_comment ADD CONSTRAINT FK_89DC4D52F8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_support_user DROP FOREIGN KEY FK_6BE961F0A76ED395');
        $this->addSql('ALTER TABLE work_package_support_user DROP FOREIGN KEY FK_6BE961F0EF2F062C');
        $this->addSql('ALTER TABLE work_package_support_user ADD CONSTRAINT FK_6BE961F0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_support_user ADD CONSTRAINT FK_6BE961F0EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_consulted_user DROP FOREIGN KEY FK_988DBEA9A76ED395');
        $this->addSql('ALTER TABLE work_package_consulted_user DROP FOREIGN KEY FK_988DBEA9EF2F062C');
        $this->addSql('ALTER TABLE work_package_consulted_user ADD CONSTRAINT FK_988DBEA9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_consulted_user ADD CONSTRAINT FK_988DBEA9EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_informed_user DROP FOREIGN KEY FK_56D96C9BA76ED395');
        $this->addSql('ALTER TABLE work_package_informed_user DROP FOREIGN KEY FK_56D96C9BEF2F062C');
        $this->addSql('ALTER TABLE work_package_informed_user ADD CONSTRAINT FK_56D96C9BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_informed_user ADD CONSTRAINT FK_56D96C9BEF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timephase DROP FOREIGN KEY FK_4125AFFDD19302F8');
        $this->addSql('ALTER TABLE timephase ADD CONSTRAINT FK_4125AFFDD19302F8 FOREIGN KEY (assignment_id) REFERENCES assignment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE status DROP FOREIGN KEY FK_7B00651C166D1F9C');
        $this->addSql('ALTER TABLE status ADD CONSTRAINT FK_7B00651C166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE file_system DROP FOREIGN KEY FK_715A3734166D1F9C');
        $this->addSql('ALTER TABLE file_system ADD CONSTRAINT FK_715A3734166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rasci DROP FOREIGN KEY FK_EAA3E345EF2F062C');
        $this->addSql('ALTER TABLE rasci ADD CONSTRAINT FK_EAA3E345EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE status_report DROP FOREIGN KEY FK_7965DFC9166D1F9C');
        $this->addSql('ALTER TABLE status_report ADD CONSTRAINT FK_7965DFC9166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_team DROP FOREIGN KEY FK_FD716E07166D1F9C');
        $this->addSql('ALTER TABLE project_team DROP FOREIGN KEY FK_FD716E07727ACA70');
        $this->addSql('ALTER TABLE project_team ADD CONSTRAINT FK_FD716E07166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_team ADD CONSTRAINT FK_FD716E07727ACA70 FOREIGN KEY (parent_id) REFERENCES project_team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subteam_member DROP FOREIGN KEY FK_497FDE14620E7061');
        $this->addSql('ALTER TABLE subteam_member DROP FOREIGN KEY FK_497FDE14A76ED395');
        $this->addSql('ALTER TABLE subteam_member ADD CONSTRAINT FK_497FDE14620E7061 FOREIGN KEY (subteam_id) REFERENCES subteam (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subteam_member ADD CONSTRAINT FK_497FDE14A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_work_cost_type DROP FOREIGN KEY FK_5B79D261166D1F9C');
        $this->addSql('ALTER TABLE project_work_cost_type ADD CONSTRAINT FK_5B79D261166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE day DROP FOREIGN KEY FK_E5A02990A40A2C8');
        $this->addSql('ALTER TABLE day ADD CONSTRAINT FK_E5A02990A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subteam_role_subteam_member DROP FOREIGN KEY FK_C158B1E2923E94FB');
        $this->addSql('ALTER TABLE subteam_role_subteam_member DROP FOREIGN KEY FK_C158B1E2A26F4AE9');
        $this->addSql('ALTER TABLE subteam_role_subteam_member ADD CONSTRAINT FK_C158B1E2923E94FB FOREIGN KEY (subteam_role_id) REFERENCES subteam_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subteam_role_subteam_member ADD CONSTRAINT FK_C158B1E2A26F4AE9 FOREIGN KEY (subteam_member_id) REFERENCES subteam_member (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE info DROP FOREIGN KEY FK_CB893157166D1F9C');
        $this->addSql('ALTER TABLE info DROP FOREIGN KEY FK_CB893157CD7EB71D');
        $this->addSql('ALTER TABLE info ADD CONSTRAINT FK_CB893157166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE info ADD CONSTRAINT FK_CB893157CD7EB71D FOREIGN KEY (info_category_id) REFERENCES info_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_room DROP FOREIGN KEY FK_D403CCDA166D1F9C');
        $this->addSql('ALTER TABLE chat_room ADD CONSTRAINT FK_D403CCDA166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE38248176');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE5565D2EA');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE62BB7AEE');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE7ACB456A');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE979B1AD6');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EEB96B5643');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EEDA896A19');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EEE566340');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE38248176 FOREIGN KEY (currency_id) REFERENCES currency (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE5565D2EA FOREIGN KEY (project_scope_id) REFERENCES project_scope (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE62BB7AEE FOREIGN KEY (programme_id) REFERENCES programme (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE7ACB456A FOREIGN KEY (project_status_id) REFERENCES project_status (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEB96B5643 FOREIGN KEY (portfolio_id) REFERENCES portfolio (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEDA896A19 FOREIGN KEY (project_category_id) REFERENCES project_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEE566340 FOREIGN KEY (project_complexity_id) REFERENCES project_complexity (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project_user_favorites DROP FOREIGN KEY FK_D3ED9B3166D1F9C');
        $this->addSql('ALTER TABLE project_user_favorites DROP FOREIGN KEY FK_D3ED9B3A76ED395');
        $this->addSql('ALTER TABLE project_user_favorites ADD CONSTRAINT FK_D3ED9B3166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_user_favorites ADD CONSTRAINT FK_D3ED9B3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14166D1F9C');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA146BF700BD');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA146BF700BD FOREIGN KEY (status_id) REFERENCES note_status (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media DROP FOREIGN KEY FK_6A2CA10C5E9A90D3');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C5E9A90D3 FOREIGN KEY (file_system_id) REFERENCES file_system (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type DROP FOREIGN KEY FK_912BB2C2A40A2C8');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type DROP FOREIGN KEY FK_912BB2C2B5830A79');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type DROP FOREIGN KEY FK_912BB2C2EF2F062C');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type ADD CONSTRAINT FK_912BB2C2A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type ADD CONSTRAINT FK_912BB2C2B5830A79 FOREIGN KEY (project_work_cost_type_id) REFERENCES project_work_cost_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type ADD CONSTRAINT FK_912BB2C2EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE working_time DROP FOREIGN KEY FK_31EE2ABF9C24126');
        $this->addSql('ALTER TABLE working_time ADD CONSTRAINT FK_31EE2ABF9C24126 FOREIGN KEY (day_id) REFERENCES day (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE calendar DROP FOREIGN KEY FK_6EA9A146166D1F9C');
        $this->addSql('ALTER TABLE calendar DROP FOREIGN KEY FK_6EA9A146727ACA70');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A146166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A146727ACA70 FOREIGN KEY (parent_id) REFERENCES calendar (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE risk_strategy DROP FOREIGN KEY FK_F26F0682166D1F9C');
        $this->addSql('ALTER TABLE risk_strategy ADD CONSTRAINT FK_F26F0682166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_complexity DROP FOREIGN KEY FK_4043BDA9166D1F9C');
        $this->addSql('ALTER TABLE project_complexity ADD CONSTRAINT FK_4043BDA9166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE label DROP FOREIGN KEY FK_EA750E8166D1F9C');
        $this->addSql('ALTER TABLE label ADD CONSTRAINT FK_EA750E8166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lesson DROP FOREIGN KEY FK_F87474F38E744ACD');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F38E744ACD FOREIGN KEY (project_close_down_id) REFERENCES project_close_down (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE opportunity_strategy DROP FOREIGN KEY FK_3B63A5FE166D1F9C');
        $this->addSql('ALTER TABLE opportunity_strategy ADD CONSTRAINT FK_3B63A5FE166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_limitation DROP FOREIGN KEY FK_4A229160166D1F9C');
        $this->addSql('ALTER TABLE project_limitation DROP FOREIGN KEY FK_4A2291602576E0FD');
        $this->addSql('ALTER TABLE project_limitation ADD CONSTRAINT FK_4A229160166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_limitation ADD CONSTRAINT FK_4A2291602576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE status_report_config DROP FOREIGN KEY FK_D0B1AB76166D1F9C');
        $this->addSql('ALTER TABLE status_report_config ADD CONSTRAINT FK_D0B1AB76166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE measure_comment DROP FOREIGN KEY FK_F0F8614A76ED395');
        $this->addSql('ALTER TABLE measure_comment ADD CONSTRAINT FK_F0F8614A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project_close_down DROP FOREIGN KEY FK_70212FF2166D1F9C');
        $this->addSql('ALTER TABLE project_close_down ADD CONSTRAINT FK_70212FF2166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7166D1F9C');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7A76ED395');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7DE12AB56');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7DED0E39F');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7EF666483');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7DED0E39F FOREIGN KEY (opportunity_strategy_id) REFERENCES opportunity_strategy (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7EF666483 FOREIGN KEY (opportunity_status_id) REFERENCES opportunity_status (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE48166D1F9C');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE48FFB4008B');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE48166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE48FFB4008B FOREIGN KEY (decision_category_id) REFERENCES decision_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation_objective DROP FOREIGN KEY FK_6B963A858E744ACD');
        $this->addSql('ALTER TABLE evaluation_objective ADD CONSTRAINT FK_6B963A858E744ACD FOREIGN KEY (project_close_down_id) REFERENCES project_close_down (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541166D1F9C');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541A76ED395');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541B61C5537');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541C82B95B3');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541DE12AB56');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541FA7D163');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541B61C5537 FOREIGN KEY (risk_status_id) REFERENCES risk_status (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541C82B95B3 FOREIGN KEY (risk_category_id) REFERENCES risk_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541FA7D163 FOREIGN KEY (risk_strategy_id) REFERENCES risk_strategy (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859166D1F9C');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859A76ED395');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subteam DROP FOREIGN KEY FK_1D55D494166D1F9C');
        $this->addSql('ALTER TABLE subteam ADD CONSTRAINT FK_1D55D494166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_category DROP FOREIGN KEY FK_3B02921A166D1F9C');
        $this->addSql('ALTER TABLE project_category ADD CONSTRAINT FK_3B02921A166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_invite DROP FOREIGN KEY FK_B1F9570E166D1F9C');
        $this->addSql('ALTER TABLE team_invite ADD CONSTRAINT FK_B1F9570E166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_objective DROP FOREIGN KEY FK_A8AAB4D6166D1F9C');
        $this->addSql('ALTER TABLE project_objective DROP FOREIGN KEY FK_A8AAB4D62576E0FD');
        $this->addSql('ALTER TABLE project_objective ADD CONSTRAINT FK_A8AAB4D6166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_objective ADD CONSTRAINT FK_A8AAB4D62576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_agenda DROP FOREIGN KEY FK_2C85F935385A88B7');
        $this->addSql('ALTER TABLE meeting_agenda ADD CONSTRAINT FK_2C85F935385A88B7 FOREIGN KEY (responsibility_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project_module DROP FOREIGN KEY FK_1B80CD62166D1F9C');
        $this->addSql('ALTER TABLE project_module ADD CONSTRAINT FK_1B80CD62166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment DROP FOREIGN KEY FK_30C544BA8E25B2F5');
        $this->addSql('ALTER TABLE assignment DROP FOREIGN KEY FK_30C544BAEF2F062C');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BA8E25B2F5 FOREIGN KEY (work_package_project_work_cost_type_id) REFERENCES work_package_project_work_cost_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BAEF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D296CD8AE');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D4C3A3BB');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment_method (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE unit DROP FOREIGN KEY FK_DCBB0C53166D1F9C');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C53166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE measure DROP FOREIGN KEY FK_80071925A76ED395');
        $this->addSql('ALTER TABLE measure ADD CONSTRAINT FK_80071925A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project_role DROP FOREIGN KEY FK_6EF84272166D1F9C');
        $this->addSql('ALTER TABLE project_role ADD CONSTRAINT FK_6EF84272166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE communication DROP FOREIGN KEY FK_F9AFB5EB166D1F9C');
        $this->addSql('ALTER TABLE communication DROP FOREIGN KEY FK_F9AFB5EBA40BC2D5');
        $this->addSql('ALTER TABLE communication ADD CONSTRAINT FK_F9AFB5EB166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE communication ADD CONSTRAINT FK_F9AFB5EBA40BC2D5 FOREIGN KEY (schedule_id) REFERENCES schedule (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE communication_participant DROP FOREIGN KEY FK_FCFF88551C2D1E0C');
        $this->addSql('ALTER TABLE communication_participant DROP FOREIGN KEY FK_FCFF8855A76ED395');
        $this->addSql('ALTER TABLE communication_participant ADD CONSTRAINT FK_FCFF88551C2D1E0C FOREIGN KEY (communication_id) REFERENCES communication (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE communication_participant ADD CONSTRAINT FK_FCFF8855A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE close_down_action DROP FOREIGN KEY FK_18A90D158E744ACD');
        $this->addSql('ALTER TABLE close_down_action ADD CONSTRAINT FK_18A90D158E744ACD FOREIGN KEY (project_close_down_id) REFERENCES project_close_down (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526CA76ED395');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resource DROP FOREIGN KEY FK_BC91F416166D1F9C');
        $this->addSql('ALTER TABLE resource DROP FOREIGN KEY FK_BC91F4163170DFF0');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT FK_BC91F416166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT FK_BC91F4163170DFF0 FOREIGN KEY (project_user_id) REFERENCES project_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_department DROP FOREIGN KEY FK_D5BB9AB8166D1F9C');
        $this->addSql('ALTER TABLE project_department DROP FOREIGN KEY FK_D5BB9AB8B5830A79');
        $this->addSql('ALTER TABLE project_department ADD CONSTRAINT FK_D5BB9AB8166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_department ADD CONSTRAINT FK_D5BB9AB8B5830A79 FOREIGN KEY (project_work_cost_type_id) REFERENCES project_work_cost_type (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project_scope DROP FOREIGN KEY FK_13FA5C4D166D1F9C');
        $this->addSql('ALTER TABLE project_scope ADD CONSTRAINT FK_13FA5C4D166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_user DROP FOREIGN KEY FK_B4021E51166D1F9C');
        $this->addSql('ALTER TABLE project_user DROP FOREIGN KEY FK_B4021E51A76ED395');
        $this->addSql('ALTER TABLE project_user DROP FOREIGN KEY FK_B4021E51BF72D4CB');
        $this->addSql('ALTER TABLE project_user DROP FOREIGN KEY FK_B4021E51DA896A19');
        $this->addSql('ALTER TABLE project_user ADD CONSTRAINT FK_B4021E51166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_user ADD CONSTRAINT FK_B4021E51A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project_user ADD CONSTRAINT FK_B4021E51BF72D4CB FOREIGN KEY (project_team_id) REFERENCES project_team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project_user ADD CONSTRAINT FK_B4021E51DA896A19 FOREIGN KEY (project_category_id) REFERENCES project_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE custom_field_value DROP FOREIGN KEY FK_EC7B05A1E5E0D4');
        $this->addSql('ALTER TABLE custom_field_value ADD CONSTRAINT FK_EC7B05A1E5E0D4 FOREIGN KEY (custom_field_id) REFERENCES custom_field (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cost DROP FOREIGN KEY FK_182694FC166D1F9C');
        $this->addSql('ALTER TABLE cost DROP FOREIGN KEY FK_182694FC89329D25');
        $this->addSql('ALTER TABLE cost DROP FOREIGN KEY FK_182694FCEF2F062C');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FC166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FC89329D25 FOREIGN KEY (resource_id) REFERENCES resource (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FCEF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE work_package_status DROP FOREIGN KEY FK_640F3F0C166D1F9C');
        $this->addSql('ALTER TABLE work_package_status ADD CONSTRAINT FK_640F3F0C166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE todo DROP FOREIGN KEY FK_5A0EB6A0166D1F9C');
        $this->addSql('ALTER TABLE todo DROP FOREIGN KEY FK_5A0EB6A06BF700BD');
        $this->addSql('ALTER TABLE todo DROP FOREIGN KEY FK_5A0EB6A07A86D49F');
        $this->addSql('ALTER TABLE todo ADD CONSTRAINT FK_5A0EB6A0166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE todo ADD CONSTRAINT FK_5A0EB6A06BF700BD FOREIGN KEY (status_id) REFERENCES todo_status (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE todo ADD CONSTRAINT FK_5A0EB6A07A86D49F FOREIGN KEY (todo_category_id) REFERENCES todo_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_cost_type DROP FOREIGN KEY FK_C1FA0B41166D1F9C');
        $this->addSql('ALTER TABLE project_cost_type ADD CONSTRAINT FK_C1FA0B41166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE distribution_list DROP FOREIGN KEY FK_4C7574ACA76ED395');
        $this->addSql('ALTER TABLE distribution_list ADD CONSTRAINT FK_4C7574ACA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE distribution_list_user DROP FOREIGN KEY FK_8FCA49BCA76ED395');
        $this->addSql('ALTER TABLE distribution_list_user DROP FOREIGN KEY FK_8FCA49BCDD1F5839');
        $this->addSql('ALTER TABLE distribution_list_user ADD CONSTRAINT FK_8FCA49BCA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE distribution_list_user ADD CONSTRAINT FK_8FCA49BCDD1F5839 FOREIGN KEY (distribution_list_id) REFERENCES distribution_list (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139166D1F9C');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E1393E269397');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139A76ED395');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E1393E269397 FOREIGN KEY (meeting_category_id) REFERENCES meeting_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE project_deliverable DROP FOREIGN KEY FK_69B253BA166D1F9C');
        $this->addSql('ALTER TABLE project_deliverable DROP FOREIGN KEY FK_69B253BA2576E0FD');
        $this->addSql('ALTER TABLE project_deliverable ADD CONSTRAINT FK_69B253BA166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_deliverable ADD CONSTRAINT FK_69B253BA2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_status DROP FOREIGN KEY FK_6CA48E56166D1F9C');
        $this->addSql('ALTER TABLE project_status ADD CONSTRAINT FK_6CA48E56166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F166D1F9C');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F1819BCFA');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F30354A65');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F78CED90B');
        $this->addSql('ALTER TABLE message CHANGE from_id from_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F1819BCFA FOREIGN KEY (chat_room_id) REFERENCES chat_room (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F30354A65 FOREIGN KEY (to_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F78CED90B FOREIGN KEY (from_id) REFERENCES user (id) ON DELETE SET NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf('mysql' != $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE color_status (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, color VARCHAR(7) NOT NULL COLLATE utf8mb4_unicode_ci, sequence INT DEFAULT 0 NOT NULL, description LONGTEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci, code VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, UNIQUE INDEX UNIQ_5E1E7BEE77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE assignment DROP FOREIGN KEY FK_30C544BAEF2F062C');
        $this->addSql('ALTER TABLE assignment DROP FOREIGN KEY FK_30C544BA8E25B2F5');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BAEF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE assignment ADD CONSTRAINT FK_30C544BA8E25B2F5 FOREIGN KEY (work_package_project_work_cost_type_id) REFERENCES work_package_project_work_cost_type (id)');
        $this->addSql('ALTER TABLE calendar DROP FOREIGN KEY FK_6EA9A146727ACA70');
        $this->addSql('ALTER TABLE calendar DROP FOREIGN KEY FK_6EA9A146166D1F9C');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A146727ACA70 FOREIGN KEY (parent_id) REFERENCES calendar (id)');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A146166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE chat_room DROP FOREIGN KEY FK_D403CCDA166D1F9C');
        $this->addSql('ALTER TABLE chat_room ADD CONSTRAINT FK_D403CCDA166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE close_down_action DROP FOREIGN KEY FK_18A90D158E744ACD');
        $this->addSql('ALTER TABLE close_down_action ADD CONSTRAINT FK_18A90D158E744ACD FOREIGN KEY (project_close_down_id) REFERENCES project_close_down (id)');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526CA76ED395');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE communication DROP FOREIGN KEY FK_F9AFB5EB166D1F9C');
        $this->addSql('ALTER TABLE communication DROP FOREIGN KEY FK_F9AFB5EBA40BC2D5');
        $this->addSql('ALTER TABLE communication ADD CONSTRAINT FK_F9AFB5EB166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE communication ADD CONSTRAINT FK_F9AFB5EBA40BC2D5 FOREIGN KEY (schedule_id) REFERENCES schedule (id)');
        $this->addSql('ALTER TABLE communication_participant DROP FOREIGN KEY FK_FCFF88551C2D1E0C');
        $this->addSql('ALTER TABLE communication_participant DROP FOREIGN KEY FK_FCFF8855A76ED395');
        $this->addSql('ALTER TABLE communication_participant ADD CONSTRAINT FK_FCFF88551C2D1E0C FOREIGN KEY (communication_id) REFERENCES communication (id)');
        $this->addSql('ALTER TABLE communication_participant ADD CONSTRAINT FK_FCFF8855A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859A76ED395');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F2859166D1F9C');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE cost DROP FOREIGN KEY FK_182694FC166D1F9C');
        $this->addSql('ALTER TABLE cost DROP FOREIGN KEY FK_182694FCEF2F062C');
        $this->addSql('ALTER TABLE cost DROP FOREIGN KEY FK_182694FC89329D25');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FC166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FCEF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FC89329D25 FOREIGN KEY (resource_id) REFERENCES resource (id)');
        $this->addSql('ALTER TABLE custom_field_value DROP FOREIGN KEY FK_EC7B05A1E5E0D4');
        $this->addSql('ALTER TABLE custom_field_value ADD CONSTRAINT FK_EC7B05A1E5E0D4 FOREIGN KEY (custom_field_id) REFERENCES custom_field (id)');
        $this->addSql('ALTER TABLE day DROP FOREIGN KEY FK_E5A02990A40A2C8');
        $this->addSql('ALTER TABLE day ADD CONSTRAINT FK_E5A02990A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id)');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE48166D1F9C');
        $this->addSql('ALTER TABLE decision DROP FOREIGN KEY FK_84ACBE48FFB4008B');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE48166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE decision ADD CONSTRAINT FK_84ACBE48FFB4008B FOREIGN KEY (decision_category_id) REFERENCES decision_category (id)');
        $this->addSql('ALTER TABLE distribution_list DROP FOREIGN KEY FK_4C7574ACA76ED395');
        $this->addSql('ALTER TABLE distribution_list ADD CONSTRAINT FK_4C7574ACA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE distribution_list_user DROP FOREIGN KEY FK_8FCA49BCDD1F5839');
        $this->addSql('ALTER TABLE distribution_list_user DROP FOREIGN KEY FK_8FCA49BCA76ED395');
        $this->addSql('ALTER TABLE distribution_list_user ADD CONSTRAINT FK_8FCA49BCDD1F5839 FOREIGN KEY (distribution_list_id) REFERENCES distribution_list (id)');
        $this->addSql('ALTER TABLE distribution_list_user ADD CONSTRAINT FK_8FCA49BCA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE evaluation_objective DROP FOREIGN KEY FK_6B963A858E744ACD');
        $this->addSql('ALTER TABLE evaluation_objective ADD CONSTRAINT FK_6B963A858E744ACD FOREIGN KEY (project_close_down_id) REFERENCES project_close_down (id)');
        $this->addSql('ALTER TABLE file_system DROP FOREIGN KEY FK_715A3734166D1F9C');
        $this->addSql('ALTER TABLE file_system ADD CONSTRAINT FK_715A3734166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE info DROP FOREIGN KEY FK_CB893157166D1F9C');
        $this->addSql('ALTER TABLE info DROP FOREIGN KEY FK_CB893157CD7EB71D');
        $this->addSql('ALTER TABLE info ADD CONSTRAINT FK_CB893157166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE info ADD CONSTRAINT FK_CB893157CD7EB71D FOREIGN KEY (info_category_id) REFERENCES info_category (id)');
        $this->addSql('ALTER TABLE label DROP FOREIGN KEY FK_EA750E8166D1F9C');
        $this->addSql('ALTER TABLE label ADD CONSTRAINT FK_EA750E8166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE lesson DROP FOREIGN KEY FK_F87474F38E744ACD');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F38E744ACD FOREIGN KEY (project_close_down_id) REFERENCES project_close_down (id)');
        $this->addSql('ALTER TABLE measure DROP FOREIGN KEY FK_80071925A76ED395');
        $this->addSql('ALTER TABLE measure ADD CONSTRAINT FK_80071925A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE measure_comment DROP FOREIGN KEY FK_F0F8614A76ED395');
        $this->addSql('ALTER TABLE measure_comment ADD CONSTRAINT FK_F0F8614A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE media DROP FOREIGN KEY FK_6A2CA10C5E9A90D3');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C5E9A90D3 FOREIGN KEY (file_system_id) REFERENCES file_system (id)');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139166D1F9C');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E1393E269397');
        $this->addSql('ALTER TABLE meeting DROP FOREIGN KEY FK_F515E139A76ED395');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E1393E269397 FOREIGN KEY (meeting_category_id) REFERENCES meeting_category (id)');
        $this->addSql('ALTER TABLE meeting ADD CONSTRAINT FK_F515E139A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE meeting_agenda DROP FOREIGN KEY FK_2C85F935385A88B7');
        $this->addSql('ALTER TABLE meeting_agenda ADD CONSTRAINT FK_2C85F935385A88B7 FOREIGN KEY (responsibility_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F166D1F9C');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F1819BCFA');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F78CED90B');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F30354A65');
        $this->addSql('ALTER TABLE message CHANGE from_id from_id INT NOT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F1819BCFA FOREIGN KEY (chat_room_id) REFERENCES chat_room (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F78CED90B FOREIGN KEY (from_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F30354A65 FOREIGN KEY (to_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14166D1F9C');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA146BF700BD');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA146BF700BD FOREIGN KEY (status_id) REFERENCES note_status (id)');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7166D1F9C');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7DED0E39F');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7A76ED395');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7DE12AB56');
        $this->addSql('ALTER TABLE opportunity DROP FOREIGN KEY FK_8389C3D7EF666483');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7DED0E39F FOREIGN KEY (opportunity_strategy_id) REFERENCES opportunity_strategy (id)');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE opportunity ADD CONSTRAINT FK_8389C3D7EF666483 FOREIGN KEY (opportunity_status_id) REFERENCES opportunity_status (id)');
        $this->addSql('ALTER TABLE opportunity_strategy DROP FOREIGN KEY FK_3B63A5FE166D1F9C');
        $this->addSql('ALTER TABLE opportunity_strategy ADD CONSTRAINT FK_3B63A5FE166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D4C3A3BB');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D296CD8AE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment_method (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE979B1AD6');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EEE566340');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EEDA896A19');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE5565D2EA');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE7ACB456A');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EEB96B5643');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE62BB7AEE');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE38248176');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEE566340 FOREIGN KEY (project_complexity_id) REFERENCES project_complexity (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEDA896A19 FOREIGN KEY (project_category_id) REFERENCES project_category (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE5565D2EA FOREIGN KEY (project_scope_id) REFERENCES project_scope (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE7ACB456A FOREIGN KEY (project_status_id) REFERENCES project_status (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEB96B5643 FOREIGN KEY (portfolio_id) REFERENCES portfolio (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE62BB7AEE FOREIGN KEY (programme_id) REFERENCES programme (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE38248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE project_category DROP FOREIGN KEY FK_3B02921A166D1F9C');
        $this->addSql('ALTER TABLE project_category ADD CONSTRAINT FK_3B02921A166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_close_down DROP FOREIGN KEY FK_70212FF2166D1F9C');
        $this->addSql('ALTER TABLE project_close_down ADD CONSTRAINT FK_70212FF2166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_complexity DROP FOREIGN KEY FK_4043BDA9166D1F9C');
        $this->addSql('ALTER TABLE project_complexity ADD CONSTRAINT FK_4043BDA9166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_cost_type DROP FOREIGN KEY FK_C1FA0B41166D1F9C');
        $this->addSql('ALTER TABLE project_cost_type ADD CONSTRAINT FK_C1FA0B41166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_deliverable DROP FOREIGN KEY FK_69B253BA2576E0FD');
        $this->addSql('ALTER TABLE project_deliverable DROP FOREIGN KEY FK_69B253BA166D1F9C');
        $this->addSql('ALTER TABLE project_deliverable ADD CONSTRAINT FK_69B253BA2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE project_deliverable ADD CONSTRAINT FK_69B253BA166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_department DROP FOREIGN KEY FK_D5BB9AB8166D1F9C');
        $this->addSql('ALTER TABLE project_department DROP FOREIGN KEY FK_D5BB9AB8B5830A79');
        $this->addSql('ALTER TABLE project_department ADD CONSTRAINT FK_D5BB9AB8166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_department ADD CONSTRAINT FK_D5BB9AB8B5830A79 FOREIGN KEY (project_work_cost_type_id) REFERENCES project_work_cost_type (id)');
        $this->addSql('ALTER TABLE project_limitation DROP FOREIGN KEY FK_4A2291602576E0FD');
        $this->addSql('ALTER TABLE project_limitation DROP FOREIGN KEY FK_4A229160166D1F9C');
        $this->addSql('ALTER TABLE project_limitation ADD CONSTRAINT FK_4A2291602576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE project_limitation ADD CONSTRAINT FK_4A229160166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_module DROP FOREIGN KEY FK_1B80CD62166D1F9C');
        $this->addSql('ALTER TABLE project_module ADD CONSTRAINT FK_1B80CD62166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_objective DROP FOREIGN KEY FK_A8AAB4D62576E0FD');
        $this->addSql('ALTER TABLE project_objective DROP FOREIGN KEY FK_A8AAB4D6166D1F9C');
        $this->addSql('ALTER TABLE project_objective ADD CONSTRAINT FK_A8AAB4D62576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE project_objective ADD CONSTRAINT FK_A8AAB4D6166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_role DROP FOREIGN KEY FK_6EF84272166D1F9C');
        $this->addSql('ALTER TABLE project_role ADD CONSTRAINT FK_6EF84272166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_scope DROP FOREIGN KEY FK_13FA5C4D166D1F9C');
        $this->addSql('ALTER TABLE project_scope ADD CONSTRAINT FK_13FA5C4D166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_status DROP FOREIGN KEY FK_6CA48E56166D1F9C');
        $this->addSql('ALTER TABLE project_status ADD CONSTRAINT FK_6CA48E56166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_team DROP FOREIGN KEY FK_FD716E07166D1F9C');
        $this->addSql('ALTER TABLE project_team DROP FOREIGN KEY FK_FD716E07727ACA70');
        $this->addSql('ALTER TABLE project_team ADD CONSTRAINT FK_FD716E07166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_team ADD CONSTRAINT FK_FD716E07727ACA70 FOREIGN KEY (parent_id) REFERENCES project_team (id)');
        $this->addSql('ALTER TABLE project_user DROP FOREIGN KEY FK_B4021E51A76ED395');
        $this->addSql('ALTER TABLE project_user DROP FOREIGN KEY FK_B4021E51166D1F9C');
        $this->addSql('ALTER TABLE project_user DROP FOREIGN KEY FK_B4021E51DA896A19');
        $this->addSql('ALTER TABLE project_user DROP FOREIGN KEY FK_B4021E51BF72D4CB');
        $this->addSql('ALTER TABLE project_user ADD CONSTRAINT FK_B4021E51A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE project_user ADD CONSTRAINT FK_B4021E51166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_user ADD CONSTRAINT FK_B4021E51DA896A19 FOREIGN KEY (project_category_id) REFERENCES project_category (id)');
        $this->addSql('ALTER TABLE project_user ADD CONSTRAINT FK_B4021E51BF72D4CB FOREIGN KEY (project_team_id) REFERENCES project_team (id)');
        $this->addSql('ALTER TABLE project_user_favorites DROP FOREIGN KEY FK_D3ED9B3166D1F9C');
        $this->addSql('ALTER TABLE project_user_favorites DROP FOREIGN KEY FK_D3ED9B3A76ED395');
        $this->addSql('ALTER TABLE project_user_favorites ADD CONSTRAINT FK_D3ED9B3166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_user_favorites ADD CONSTRAINT FK_D3ED9B3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE project_work_cost_type DROP FOREIGN KEY FK_5B79D261166D1F9C');
        $this->addSql('ALTER TABLE project_work_cost_type ADD CONSTRAINT FK_5B79D261166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE rasci DROP FOREIGN KEY FK_EAA3E345EF2F062C');
        $this->addSql('ALTER TABLE rasci ADD CONSTRAINT FK_EAA3E345EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE resource DROP FOREIGN KEY FK_BC91F416166D1F9C');
        $this->addSql('ALTER TABLE resource DROP FOREIGN KEY FK_BC91F4163170DFF0');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT FK_BC91F416166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT FK_BC91F4163170DFF0 FOREIGN KEY (project_user_id) REFERENCES project_user (id)');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541166D1F9C');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541FA7D163');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541C82B95B3');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541A76ED395');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541DE12AB56');
        $this->addSql('ALTER TABLE risk DROP FOREIGN KEY FK_7906D541B61C5537');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541FA7D163 FOREIGN KEY (risk_strategy_id) REFERENCES risk_strategy (id)');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541C82B95B3 FOREIGN KEY (risk_category_id) REFERENCES risk_category (id)');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE risk ADD CONSTRAINT FK_7906D541B61C5537 FOREIGN KEY (risk_status_id) REFERENCES risk_status (id)');
        $this->addSql('ALTER TABLE risk_strategy DROP FOREIGN KEY FK_F26F0682166D1F9C');
        $this->addSql('ALTER TABLE risk_strategy ADD CONSTRAINT FK_F26F0682166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE status DROP FOREIGN KEY FK_7B00651C166D1F9C');
        $this->addSql('ALTER TABLE status ADD CONSTRAINT FK_7B00651C166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE status_report DROP FOREIGN KEY FK_7965DFC9166D1F9C');
        $this->addSql('ALTER TABLE status_report ADD CONSTRAINT FK_7965DFC9166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE status_report_config DROP FOREIGN KEY FK_D0B1AB76166D1F9C');
        $this->addSql('ALTER TABLE status_report_config ADD CONSTRAINT FK_D0B1AB76166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE subteam DROP FOREIGN KEY FK_1D55D494166D1F9C');
        $this->addSql('ALTER TABLE subteam ADD CONSTRAINT FK_1D55D494166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE subteam_member DROP FOREIGN KEY FK_497FDE14A76ED395');
        $this->addSql('ALTER TABLE subteam_member DROP FOREIGN KEY FK_497FDE14620E7061');
        $this->addSql('ALTER TABLE subteam_member ADD CONSTRAINT FK_497FDE14A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE subteam_member ADD CONSTRAINT FK_497FDE14620E7061 FOREIGN KEY (subteam_id) REFERENCES subteam (id)');
        $this->addSql('ALTER TABLE subteam_role_subteam_member DROP FOREIGN KEY FK_C158B1E2923E94FB');
        $this->addSql('ALTER TABLE subteam_role_subteam_member DROP FOREIGN KEY FK_C158B1E2A26F4AE9');
        $this->addSql('ALTER TABLE subteam_role_subteam_member ADD CONSTRAINT FK_C158B1E2923E94FB FOREIGN KEY (subteam_role_id) REFERENCES subteam_role (id)');
        $this->addSql('ALTER TABLE subteam_role_subteam_member ADD CONSTRAINT FK_C158B1E2A26F4AE9 FOREIGN KEY (subteam_member_id) REFERENCES subteam_member (id)');
        $this->addSql('ALTER TABLE team_invite DROP FOREIGN KEY FK_B1F9570E166D1F9C');
        $this->addSql('ALTER TABLE team_invite ADD CONSTRAINT FK_B1F9570E166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE timephase DROP FOREIGN KEY FK_4125AFFDD19302F8');
        $this->addSql('ALTER TABLE timephase ADD CONSTRAINT FK_4125AFFDD19302F8 FOREIGN KEY (assignment_id) REFERENCES assignment (id)');
        $this->addSql('ALTER TABLE todo DROP FOREIGN KEY FK_5A0EB6A0166D1F9C');
        $this->addSql('ALTER TABLE todo DROP FOREIGN KEY FK_5A0EB6A07A86D49F');
        $this->addSql('ALTER TABLE todo DROP FOREIGN KEY FK_5A0EB6A06BF700BD');
        $this->addSql('ALTER TABLE todo ADD CONSTRAINT FK_5A0EB6A0166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE todo ADD CONSTRAINT FK_5A0EB6A07A86D49F FOREIGN KEY (todo_category_id) REFERENCES todo_category (id)');
        $this->addSql('ALTER TABLE todo ADD CONSTRAINT FK_5A0EB6A06BF700BD FOREIGN KEY (status_id) REFERENCES todo_status (id)');
        $this->addSql('ALTER TABLE unit DROP FOREIGN KEY FK_DCBB0C53166D1F9C');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C53166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB799091188');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB74B3E2EDA');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7166D1F9C');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7385A88B7');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7EFF0A1F4');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7A40A2C8');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB7A73A0B9D');
        $this->addSql('ALTER TABLE work_package DROP FOREIGN KEY FK_BA3DFB71010AC05');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB799091188 FOREIGN KEY (phase_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB74B3E2EDA FOREIGN KEY (milestone_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7385A88B7 FOREIGN KEY (responsibility_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7EFF0A1F4 FOREIGN KEY (accountability_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id)');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB7A73A0B9D FOREIGN KEY (work_package_status_id) REFERENCES work_package_status (id)');
        $this->addSql('ALTER TABLE work_package ADD CONSTRAINT FK_BA3DFB71010AC05 FOREIGN KEY (work_package_category_id) REFERENCES work_package_category (id)');
        $this->addSql('ALTER TABLE work_package_comment DROP FOREIGN KEY FK_89DC4D52EF2F062C');
        $this->addSql('ALTER TABLE work_package_comment DROP FOREIGN KEY FK_89DC4D52F8697D13');
        $this->addSql('ALTER TABLE work_package_comment ADD CONSTRAINT FK_89DC4D52EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package_comment ADD CONSTRAINT FK_89DC4D52F8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id)');
        $this->addSql('ALTER TABLE work_package_consulted_user DROP FOREIGN KEY FK_988DBEA9EF2F062C');
        $this->addSql('ALTER TABLE work_package_consulted_user DROP FOREIGN KEY FK_988DBEA9A76ED395');
        $this->addSql('ALTER TABLE work_package_consulted_user ADD CONSTRAINT FK_988DBEA9EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package_consulted_user ADD CONSTRAINT FK_988DBEA9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE work_package_dependency DROP FOREIGN KEY FK_14FAB8C6B3D00E54');
        $this->addSql('ALTER TABLE work_package_dependency DROP FOREIGN KEY FK_14FAB8C6C2F67723');
        $this->addSql('ALTER TABLE work_package_dependency ADD CONSTRAINT FK_14FAB8C6B3D00E54 FOREIGN KEY (dependant_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package_dependency ADD CONSTRAINT FK_14FAB8C6C2F67723 FOREIGN KEY (dependency_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package_informed_user DROP FOREIGN KEY FK_56D96C9BEF2F062C');
        $this->addSql('ALTER TABLE work_package_informed_user DROP FOREIGN KEY FK_56D96C9BA76ED395');
        $this->addSql('ALTER TABLE work_package_informed_user ADD CONSTRAINT FK_56D96C9BEF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package_informed_user ADD CONSTRAINT FK_56D96C9BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE work_package_label DROP FOREIGN KEY FK_DB7E2E3BEF2F062C');
        $this->addSql('ALTER TABLE work_package_label DROP FOREIGN KEY FK_DB7E2E3B33B92F39');
        $this->addSql('ALTER TABLE work_package_label ADD CONSTRAINT FK_DB7E2E3BEF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package_label ADD CONSTRAINT FK_DB7E2E3B33B92F39 FOREIGN KEY (label_id) REFERENCES label (id)');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type DROP FOREIGN KEY FK_912BB2C2EF2F062C');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type DROP FOREIGN KEY FK_912BB2C2B5830A79');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type DROP FOREIGN KEY FK_912BB2C2A40A2C8');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type ADD CONSTRAINT FK_912BB2C2EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type ADD CONSTRAINT FK_912BB2C2B5830A79 FOREIGN KEY (project_work_cost_type_id) REFERENCES project_work_cost_type (id)');
        $this->addSql('ALTER TABLE work_package_project_work_cost_type ADD CONSTRAINT FK_912BB2C2A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id)');
        $this->addSql('ALTER TABLE work_package_status DROP FOREIGN KEY FK_640F3F0C166D1F9C');
        $this->addSql('ALTER TABLE work_package_status ADD CONSTRAINT FK_640F3F0C166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE work_package_support_user DROP FOREIGN KEY FK_6BE961F0EF2F062C');
        $this->addSql('ALTER TABLE work_package_support_user DROP FOREIGN KEY FK_6BE961F0A76ED395');
        $this->addSql('ALTER TABLE work_package_support_user ADD CONSTRAINT FK_6BE961F0EF2F062C FOREIGN KEY (work_package_id) REFERENCES work_package (id)');
        $this->addSql('ALTER TABLE work_package_support_user ADD CONSTRAINT FK_6BE961F0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE working_time DROP FOREIGN KEY FK_31EE2ABF9C24126');
        $this->addSql('ALTER TABLE working_time ADD CONSTRAINT FK_31EE2ABF9C24126 FOREIGN KEY (day_id) REFERENCES day (id)');
    }
}
