services:
    main.admin_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.menu_builder", createAdminMainMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: admin_main }

### VALIDATION CONSTRAINTS ###
    main.team_slug_usable_constraint:
        class: MainBundle\Validator\Constraints\TeamSlugUsableValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator }

### LISTENERS ###
    main.listener.team:
        class: MainBundle\EventListener\TeamListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    main.listener.image_serialize:
        class: MainBundle\EventListener\ImageSerializeListener
        arguments:
            - "@vich_uploader.storage"
            - "@request_stack"
        tags:
            - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize }

### VOTERS ###
    main.team_voter:
        class: MainBundle\Security\TeamVoter
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: security.voter }
        public: false
