services:
    main.admin_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.admin.menu.builder", createAdminMainMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: admin_main }

### FORMS ###
    main.form.user.account_type:
        class: MainBundle\Form\User\AccountType
        arguments:
            - '@scheb_two_factor.security.google_authenticator'
        tags:
            - { name: form.type }

    main.form.locale_type:
        class: MainBundle\Form\LocaleType
        arguments:
            - '@app.locale.provider'
        tags:
            - { name: form.type }

### LISTENERS ###
    main.listener.locale:
        class: MainBundle\EventListener\LocaleListener
        arguments:
            - '@translator'
            - '@app.locale.context'
            - '@app.locale.provider'
            - '@app.container'
        tags:
            - { name: kernel.event_subscriber }

### VOTERS ###
    main.team_voter:
        class: MainBundle\Security\TeamVoter
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: security.voter }
        public: false
