services:
    main.admin_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.admin.menu.builder", createAdminMainMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: admin_main }

### FORMS ###
    main.form.user.account_type:
        class: MainBundle\Form\User\AccountType
        arguments:
            - '@scheb_two_factor.security.google_authenticator'
        tags:
            - { name: form.type }

    main.form.locale_type:
        class: MainBundle\Form\LocaleType
        arguments:
            - '@app.locale.provider'
        tags:
            - { name: form.type }

### VALIDATION CONSTRAINTS ###
    main.team_slug_usable_constraint:
        class: MainBundle\Validator\Constraints\TeamSlugUsableValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator }

### LISTENERS ###
    main.listener.team:
        class: MainBundle\EventListener\TeamListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    main.listener.image_serialize:
        class: MainBundle\EventListener\ImageSerializeListener
        arguments:
            - "@vich_uploader.storage"
            - "@request_stack"
            - '@app.resolver.user_avatar_url'
        tags:
            - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize }

    main.listener.locale:
        class: MainBundle\EventListener\LocaleListener
        arguments:
            - '@translator'
            - '@app.locale.context'
            - '@app.locale.provider'
        tags:
            - { name: kernel.event_subscriber }

### VOTERS ###
    main.team_voter:
        class: MainBundle\Security\TeamVoter
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: security.voter }
        public: false

### SUBSCRIBERS ###
    main.team_subscriber:
        class: MainBundle\Subscriber\TeamSubscriber
        arguments:
            - '%kernel.environment%'
            - '@redis.client'
        tags:
            - { name: kernel.event_subscriber }
